### ISSUE TITLE
Erro facebook

### ISSUE THREAD

**Issue by wubuyun** [karliuka/m2.SocialLogin#1]
Magento 2.1.11
Fatal error: Uncaught Error: Call to a member function getProviderUid() on boolean in /home/nihaomodas.com.br/public/vendor/faonni/module-social-login/Observer/ObtainTokenObserver.php:170 Stack trace: #0 /home/nihaomodas.com.br/public/vendor/magento/framework/Event/Invoker/InvokerDefault.php(73): Faonni\SocialLogin\Observer\ObtainTokenObserver->execute(Object(Magento\Framework\Event\Observer)) #1 /home/nihaomodas.com.br/public/vendor/magento/framework/Event/Invoker/InvokerDefault.php(61): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Faonni\SocialLogin\Observer\ObtainTokenObserver), Object(Magento\Framework\Event\Observer)) #2 /home/nihaomodas.com.br/public/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer)) #3 /home/nihaomodas.com.br/public/var/generation/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch('faonni_sociallo...', Array) #4 /home/nihaomodas.c in /home/nihaomodas.com.br/public/vendor/faonni/module-social-login/Observer/ObtainTokenObserver.php on line 170

**Comment by karliuka** [comment]
Ok, I will take a look

**Comment by karliuka** [comment]
This is fixed. Please, update module.

**Comment by wubuyun** [comment]
Thanks..
