### ISSUE TITLE
Checkout Page and Login Popup

### ISSUE THREAD

**Issue by marcelowu** [karliuka/m2.SocialLogin#2]
Login Page, Register Page,--> ok
Checkout Page and Login Popup, when you click the checkout button and guest checkout is disabled not show...
ex:
https://github.com/feelinc/magento2-social-login/raw/master/screenshots/popup.jpg?raw=true
https://github.com/feelinc/magento2-social-login/raw/master/screenshots/checkout.jpg?raw=true

**Comment by karliuka** [comment]
Ok, I will take a look

**Comment by karliuka** [comment]
Please test, release 2.1.3
